# yolov4 parameters
network: 'yolov4'

input_shape: [1,3,608,608]
class_num: 5

label_file_path: 'coco_labels.txt'
onnx_path: 'yolov4_608.onnx'
engine_path: 'yolov4_608_fp16.trt'

int8_calibration: False  # int8量化
letter_box: False  # 是否采用yolov5的预测方式

neck: 'PAN' # 'FPN'-yolov3  'PAN'-yolov4
conf_threshold: 0.5
nms_threshold: 0.45
num_anchors: [3,  3,  3]
stride: [8, 16, 32]  # PAN, yolov3.FPN->reverse
yolo_masks: [[0, 1, 2], [3, 4, 5], [6, 7, 8]]  # yolov3 reverse, 必须是list
anchors: [[12, 16], [19, 36], [40, 28], [36, 75], [76, 55], [72, 146], [142, 110], [192, 243], [459, 401]]

# onnx操作是否添加sigmoid操作，一般都是yolov4新的预测方式使用
onnx_sigmoid: False